basic_p/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATES URLS!
app_name ='basic_app'
urlpatterns =[
    url(r'^register/$',views.register,name ="register"),
    url(r'^user_login/$',views.user_login,name ="login")
]

basic_p/basic_p/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index, name ="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include("basic_app.urls")),
    url(r'^logout/$',views.user_logout,name ='logout'),
    url(r'^special/',views.special,name ="special")
    ]

basic_p/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create models here.

class UserProfileInfo(models.Model):

    user =models.OneToOneField(User, on_delete = models.CASCADE)

    #addtional
    portfolio_site = models.URLField(blank =True)
    profile_pic = models.ImageField(upload_to ='profile_pics',blank =True)

    def __str__(self):

        return self.user.username

basic_p/basic_app/views.py
from django.shortcuts import render
from basic_app.form import UserForm, UserProfileInfoForm

#Importing some method
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse

from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    return render(request,'htmls/index.html')
@login_required
def special(request):
    return HttpResponse("hey! you login nicely")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index.html'))


def register(request):

    registered =False

    if request.method == "POST":
        user_form = UserForm(data =request.POST)
        profile_form =UserProfileInfoForm(data =request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user =user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit =False)

            if 'profile_pic' in request.FILES:
                profile.profile_pic =request.FILES['profile_pic']

            profile.save()
            registered =True



        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form =UserForm()
        profile_form =UserProfileInfoForm()


    return render(request,'htmls/registrations.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method =="POST":
        username =request.POST.get('username')
        password =request.POST.get('password')
        user =authenticate(username =username,password =password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("SOMEONE TRIED TO LOGIN AND FAILED")
            print("user name {} and password {}".format(username,password))
            return HttpResponse("invailid login details supplied!")
    else:
        return render(request,'htmls/login.html',{})

basic_p/templates/htmls/base.html
<!DOCTYPE html>
{% load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static "style/bootstrap.css"%}">

  </head>
  <body>

    <nav class = "navbar navbar-dark bg-dark navbar-static-top">
      <div class="container">
        <ul class ="nav navbar-nav">
          <li><a class ="navbar-brand" href="{%url 'index'%}">Home</a></li>
          <li><a class=" navbar-link" href="{% url "admin:index"%}">Admin</a></li>
          <li><a class="navbar-link" href ="{%url "basic_app:register"%}">Register</a></li>

          

        </ul>


      </div>

    </nav>
    <h1 class="jumbotron">WELCOME</h1>

    <div class="container">
      {% block body_block%}
      {% endblock%}


    </div>

  </body>
</html>

basic_p/templates/htmls/index.html
<!DOCTYPE html>
{% extends "htmls/base.html"%}
{% block body_block %}

<div class="jumbotron">
  <h1>DJAGO LEVEL FIVE</h1>
  

</div>
{% endblock %}

basic_p/templates/htmls/login.html
<!DOCTYPE html>
{% extends 'htmls/base.html' %}
{% block body_block%}
<div class="jumbotron">
  <h1>please Login</h1>
  <form class="jumbotron" action="{% url 'basic_app:user_login'%}" method="post">
    {%csrf_token%}
    <label for="username">User Name</label>
    <input type="text" name="username" placeholder="Enter your user name">
    <label for="password">Password</label>
    <input type="password" name="password" placeholder="Enter password">
    <input type="submit" Class="btn btn-primary"value="Login">

  </form>

</div>


{% endblock%}

basic_p/templates/htmls/registrations.html
<!DOCTYPE html>
{% extends "htmls/base.html"%}
{% load static%}
{% block body_block %}

<div class ="container">
  {% if registered%}
  <h1>Thanks for registration here</h1>
  {%else%}
  <h1 class="jumbotron">Register here</h1>
  <h3> Fill out this form</h3>

  <form class="jumbotron" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" class = "btn btn-primary"value="Register">
  </form>
  {% endif%}

</div>
{% endblock%}